### ISSUE TITLE
Charity comission does not parse

### ISSUE THREAD

**Issue by pwaller** [openregister/address-matching-data#13]
Reading [`bulk/charity-commission/addresses.tsv`](https://github.com/openregister/address-matching-data/blob/915a600d099de736b20369d66a68dc7be105d921/bulk/charity-commission/addresses.tsv) with the standard go CSV reader, I get this error:

```
line 7006, column 31: extraneous " in field
```

Line 7006 reads:

```
charity:1051144 "OFF THE RECORD" YOUTH COUNSELLING CROYDON      OFF THE RECORD YOUTH COUNSELLING, 72 QUEENS ROAD, CROYDON       CR0 2PR
```

**Comment by pwaller** [comment]
food-hygiene has the same problem.

```
2016/08/01 14:47:54 line 14501, column 12: bare " in non-quoted-field
```

```
FHRS:719526     "Go" Take Out Sandwich & Pasty Bar      Go, Rutland Square, Bakewell, Derbyshire        DE45 1BT        070     [53.21351,-1.67545]
```

**Comment by psd** [comment]
Quotes are allowable in content in the .tsv format and can be read using the csv module as in this [gist](https://gist.github.com/psd/a88bd35cc2b0fbd95ed79c9dfa3250bb).
